// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CFRNode.proto

public final class CFRNodeOuterClass {
  private CFRNodeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CFRNodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CFRNode)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated float regret_sum = 1;</code>
     * @return A list containing the regretSum.
     */
    java.util.List<java.lang.Float> getRegretSumList();
    /**
     * <code>repeated float regret_sum = 1;</code>
     * @return The count of regretSum.
     */
    int getRegretSumCount();
    /**
     * <code>repeated float regret_sum = 1;</code>
     * @param index The index of the element to return.
     * @return The regretSum at the given index.
     */
    float getRegretSum(int index);

    /**
     * <code>repeated float strategy = 2;</code>
     * @return A list containing the strategy.
     */
    java.util.List<java.lang.Float> getStrategyList();
    /**
     * <code>repeated float strategy = 2;</code>
     * @return The count of strategy.
     */
    int getStrategyCount();
    /**
     * <code>repeated float strategy = 2;</code>
     * @param index The index of the element to return.
     * @return The strategy at the given index.
     */
    float getStrategy(int index);

    /**
     * <code>repeated float strategy_sum = 3;</code>
     * @return A list containing the strategySum.
     */
    java.util.List<java.lang.Float> getStrategySumList();
    /**
     * <code>repeated float strategy_sum = 3;</code>
     * @return The count of strategySum.
     */
    int getStrategySumCount();
    /**
     * <code>repeated float strategy_sum = 3;</code>
     * @param index The index of the element to return.
     * @return The strategySum at the given index.
     */
    float getStrategySum(int index);

    /**
     * <code>int32 num_actions = 4;</code>
     * @return The numActions.
     */
    int getNumActions();
  }
  /**
   * Protobuf type {@code CFRNode}
   */
  public static final class CFRNode extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CFRNode)
      CFRNodeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CFRNode.newBuilder() to construct.
    private CFRNode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CFRNode() {
      regretSum_ = emptyFloatList();
      strategy_ = emptyFloatList();
      strategySum_ = emptyFloatList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CFRNode();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CFRNodeOuterClass.internal_static_CFRNode_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CFRNodeOuterClass.internal_static_CFRNode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CFRNodeOuterClass.CFRNode.class, CFRNodeOuterClass.CFRNode.Builder.class);
    }

    public static final int REGRET_SUM_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.FloatList regretSum_;
    /**
     * <code>repeated float regret_sum = 1;</code>
     * @return A list containing the regretSum.
     */
    @java.lang.Override
    public java.util.List<java.lang.Float>
        getRegretSumList() {
      return regretSum_;
    }
    /**
     * <code>repeated float regret_sum = 1;</code>
     * @return The count of regretSum.
     */
    public int getRegretSumCount() {
      return regretSum_.size();
    }
    /**
     * <code>repeated float regret_sum = 1;</code>
     * @param index The index of the element to return.
     * @return The regretSum at the given index.
     */
    public float getRegretSum(int index) {
      return regretSum_.getFloat(index);
    }
    private int regretSumMemoizedSerializedSize = -1;

    public static final int STRATEGY_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.FloatList strategy_;
    /**
     * <code>repeated float strategy = 2;</code>
     * @return A list containing the strategy.
     */
    @java.lang.Override
    public java.util.List<java.lang.Float>
        getStrategyList() {
      return strategy_;
    }
    /**
     * <code>repeated float strategy = 2;</code>
     * @return The count of strategy.
     */
    public int getStrategyCount() {
      return strategy_.size();
    }
    /**
     * <code>repeated float strategy = 2;</code>
     * @param index The index of the element to return.
     * @return The strategy at the given index.
     */
    public float getStrategy(int index) {
      return strategy_.getFloat(index);
    }
    private int strategyMemoizedSerializedSize = -1;

    public static final int STRATEGY_SUM_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.FloatList strategySum_;
    /**
     * <code>repeated float strategy_sum = 3;</code>
     * @return A list containing the strategySum.
     */
    @java.lang.Override
    public java.util.List<java.lang.Float>
        getStrategySumList() {
      return strategySum_;
    }
    /**
     * <code>repeated float strategy_sum = 3;</code>
     * @return The count of strategySum.
     */
    public int getStrategySumCount() {
      return strategySum_.size();
    }
    /**
     * <code>repeated float strategy_sum = 3;</code>
     * @param index The index of the element to return.
     * @return The strategySum at the given index.
     */
    public float getStrategySum(int index) {
      return strategySum_.getFloat(index);
    }
    private int strategySumMemoizedSerializedSize = -1;

    public static final int NUM_ACTIONS_FIELD_NUMBER = 4;
    private int numActions_ = 0;
    /**
     * <code>int32 num_actions = 4;</code>
     * @return The numActions.
     */
    @java.lang.Override
    public int getNumActions() {
      return numActions_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getRegretSumList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(regretSumMemoizedSerializedSize);
      }
      for (int i = 0; i < regretSum_.size(); i++) {
        output.writeFloatNoTag(regretSum_.getFloat(i));
      }
      if (getStrategyList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(strategyMemoizedSerializedSize);
      }
      for (int i = 0; i < strategy_.size(); i++) {
        output.writeFloatNoTag(strategy_.getFloat(i));
      }
      if (getStrategySumList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(strategySumMemoizedSerializedSize);
      }
      for (int i = 0; i < strategySum_.size(); i++) {
        output.writeFloatNoTag(strategySum_.getFloat(i));
      }
      if (numActions_ != 0) {
        output.writeInt32(4, numActions_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 4 * getRegretSumList().size();
        size += dataSize;
        if (!getRegretSumList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        regretSumMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        dataSize = 4 * getStrategyList().size();
        size += dataSize;
        if (!getStrategyList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        strategyMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        dataSize = 4 * getStrategySumList().size();
        size += dataSize;
        if (!getStrategySumList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        strategySumMemoizedSerializedSize = dataSize;
      }
      if (numActions_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, numActions_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CFRNodeOuterClass.CFRNode)) {
        return super.equals(obj);
      }
      CFRNodeOuterClass.CFRNode other = (CFRNodeOuterClass.CFRNode) obj;

      if (!getRegretSumList()
          .equals(other.getRegretSumList())) return false;
      if (!getStrategyList()
          .equals(other.getStrategyList())) return false;
      if (!getStrategySumList()
          .equals(other.getStrategySumList())) return false;
      if (getNumActions()
          != other.getNumActions()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRegretSumCount() > 0) {
        hash = (37 * hash) + REGRET_SUM_FIELD_NUMBER;
        hash = (53 * hash) + getRegretSumList().hashCode();
      }
      if (getStrategyCount() > 0) {
        hash = (37 * hash) + STRATEGY_FIELD_NUMBER;
        hash = (53 * hash) + getStrategyList().hashCode();
      }
      if (getStrategySumCount() > 0) {
        hash = (37 * hash) + STRATEGY_SUM_FIELD_NUMBER;
        hash = (53 * hash) + getStrategySumList().hashCode();
      }
      hash = (37 * hash) + NUM_ACTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getNumActions();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CFRNodeOuterClass.CFRNode parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CFRNodeOuterClass.CFRNode parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CFRNodeOuterClass.CFRNode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CFRNodeOuterClass.CFRNode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CFRNodeOuterClass.CFRNode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CFRNodeOuterClass.CFRNode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CFRNodeOuterClass.CFRNode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CFRNodeOuterClass.CFRNode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CFRNodeOuterClass.CFRNode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CFRNodeOuterClass.CFRNode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CFRNodeOuterClass.CFRNode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CFRNodeOuterClass.CFRNode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CFRNodeOuterClass.CFRNode prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CFRNode}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CFRNode)
        CFRNodeOuterClass.CFRNodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CFRNodeOuterClass.internal_static_CFRNode_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CFRNodeOuterClass.internal_static_CFRNode_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CFRNodeOuterClass.CFRNode.class, CFRNodeOuterClass.CFRNode.Builder.class);
      }

      // Construct using CFRNodeOuterClass.CFRNode.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        regretSum_ = emptyFloatList();
        strategy_ = emptyFloatList();
        strategySum_ = emptyFloatList();
        numActions_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CFRNodeOuterClass.internal_static_CFRNode_descriptor;
      }

      @java.lang.Override
      public CFRNodeOuterClass.CFRNode getDefaultInstanceForType() {
        return CFRNodeOuterClass.CFRNode.getDefaultInstance();
      }

      @java.lang.Override
      public CFRNodeOuterClass.CFRNode build() {
        CFRNodeOuterClass.CFRNode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public CFRNodeOuterClass.CFRNode buildPartial() {
        CFRNodeOuterClass.CFRNode result = new CFRNodeOuterClass.CFRNode(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(CFRNodeOuterClass.CFRNode result) {
        if (((bitField0_ & 0x00000001) != 0)) {
          regretSum_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.regretSum_ = regretSum_;
        if (((bitField0_ & 0x00000002) != 0)) {
          strategy_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.strategy_ = strategy_;
        if (((bitField0_ & 0x00000004) != 0)) {
          strategySum_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.strategySum_ = strategySum_;
      }

      private void buildPartial0(CFRNodeOuterClass.CFRNode result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.numActions_ = numActions_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CFRNodeOuterClass.CFRNode) {
          return mergeFrom((CFRNodeOuterClass.CFRNode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CFRNodeOuterClass.CFRNode other) {
        if (other == CFRNodeOuterClass.CFRNode.getDefaultInstance()) return this;
        if (!other.regretSum_.isEmpty()) {
          if (regretSum_.isEmpty()) {
            regretSum_ = other.regretSum_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRegretSumIsMutable();
            regretSum_.addAll(other.regretSum_);
          }
          onChanged();
        }
        if (!other.strategy_.isEmpty()) {
          if (strategy_.isEmpty()) {
            strategy_ = other.strategy_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureStrategyIsMutable();
            strategy_.addAll(other.strategy_);
          }
          onChanged();
        }
        if (!other.strategySum_.isEmpty()) {
          if (strategySum_.isEmpty()) {
            strategySum_ = other.strategySum_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureStrategySumIsMutable();
            strategySum_.addAll(other.strategySum_);
          }
          onChanged();
        }
        if (other.getNumActions() != 0) {
          setNumActions(other.getNumActions());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {
                float v = input.readFloat();
                ensureRegretSumIsMutable();
                regretSum_.addFloat(v);
                break;
              } // case 13
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureRegretSumIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  regretSum_.addFloat(input.readFloat());
                }
                input.popLimit(limit);
                break;
              } // case 10
              case 21: {
                float v = input.readFloat();
                ensureStrategyIsMutable();
                strategy_.addFloat(v);
                break;
              } // case 21
              case 18: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureStrategyIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  strategy_.addFloat(input.readFloat());
                }
                input.popLimit(limit);
                break;
              } // case 18
              case 29: {
                float v = input.readFloat();
                ensureStrategySumIsMutable();
                strategySum_.addFloat(v);
                break;
              } // case 29
              case 26: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureStrategySumIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  strategySum_.addFloat(input.readFloat());
                }
                input.popLimit(limit);
                break;
              } // case 26
              case 32: {
                numActions_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.FloatList regretSum_ = emptyFloatList();
      private void ensureRegretSumIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          regretSum_ = mutableCopy(regretSum_);
          bitField0_ |= 0x00000001;
        }
      }
      /**
       * <code>repeated float regret_sum = 1;</code>
       * @return A list containing the regretSum.
       */
      public java.util.List<java.lang.Float>
          getRegretSumList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(regretSum_) : regretSum_;
      }
      /**
       * <code>repeated float regret_sum = 1;</code>
       * @return The count of regretSum.
       */
      public int getRegretSumCount() {
        return regretSum_.size();
      }
      /**
       * <code>repeated float regret_sum = 1;</code>
       * @param index The index of the element to return.
       * @return The regretSum at the given index.
       */
      public float getRegretSum(int index) {
        return regretSum_.getFloat(index);
      }
      /**
       * <code>repeated float regret_sum = 1;</code>
       * @param index The index to set the value at.
       * @param value The regretSum to set.
       * @return This builder for chaining.
       */
      public Builder setRegretSum(
          int index, float value) {
        
        ensureRegretSumIsMutable();
        regretSum_.setFloat(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float regret_sum = 1;</code>
       * @param value The regretSum to add.
       * @return This builder for chaining.
       */
      public Builder addRegretSum(float value) {
        
        ensureRegretSumIsMutable();
        regretSum_.addFloat(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float regret_sum = 1;</code>
       * @param values The regretSum to add.
       * @return This builder for chaining.
       */
      public Builder addAllRegretSum(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureRegretSumIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, regretSum_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float regret_sum = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRegretSum() {
        regretSum_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.FloatList strategy_ = emptyFloatList();
      private void ensureStrategyIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          strategy_ = mutableCopy(strategy_);
          bitField0_ |= 0x00000002;
        }
      }
      /**
       * <code>repeated float strategy = 2;</code>
       * @return A list containing the strategy.
       */
      public java.util.List<java.lang.Float>
          getStrategyList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(strategy_) : strategy_;
      }
      /**
       * <code>repeated float strategy = 2;</code>
       * @return The count of strategy.
       */
      public int getStrategyCount() {
        return strategy_.size();
      }
      /**
       * <code>repeated float strategy = 2;</code>
       * @param index The index of the element to return.
       * @return The strategy at the given index.
       */
      public float getStrategy(int index) {
        return strategy_.getFloat(index);
      }
      /**
       * <code>repeated float strategy = 2;</code>
       * @param index The index to set the value at.
       * @param value The strategy to set.
       * @return This builder for chaining.
       */
      public Builder setStrategy(
          int index, float value) {
        
        ensureStrategyIsMutable();
        strategy_.setFloat(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float strategy = 2;</code>
       * @param value The strategy to add.
       * @return This builder for chaining.
       */
      public Builder addStrategy(float value) {
        
        ensureStrategyIsMutable();
        strategy_.addFloat(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float strategy = 2;</code>
       * @param values The strategy to add.
       * @return This builder for chaining.
       */
      public Builder addAllStrategy(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureStrategyIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, strategy_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float strategy = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStrategy() {
        strategy_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.FloatList strategySum_ = emptyFloatList();
      private void ensureStrategySumIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          strategySum_ = mutableCopy(strategySum_);
          bitField0_ |= 0x00000004;
        }
      }
      /**
       * <code>repeated float strategy_sum = 3;</code>
       * @return A list containing the strategySum.
       */
      public java.util.List<java.lang.Float>
          getStrategySumList() {
        return ((bitField0_ & 0x00000004) != 0) ?
                 java.util.Collections.unmodifiableList(strategySum_) : strategySum_;
      }
      /**
       * <code>repeated float strategy_sum = 3;</code>
       * @return The count of strategySum.
       */
      public int getStrategySumCount() {
        return strategySum_.size();
      }
      /**
       * <code>repeated float strategy_sum = 3;</code>
       * @param index The index of the element to return.
       * @return The strategySum at the given index.
       */
      public float getStrategySum(int index) {
        return strategySum_.getFloat(index);
      }
      /**
       * <code>repeated float strategy_sum = 3;</code>
       * @param index The index to set the value at.
       * @param value The strategySum to set.
       * @return This builder for chaining.
       */
      public Builder setStrategySum(
          int index, float value) {
        
        ensureStrategySumIsMutable();
        strategySum_.setFloat(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float strategy_sum = 3;</code>
       * @param value The strategySum to add.
       * @return This builder for chaining.
       */
      public Builder addStrategySum(float value) {
        
        ensureStrategySumIsMutable();
        strategySum_.addFloat(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float strategy_sum = 3;</code>
       * @param values The strategySum to add.
       * @return This builder for chaining.
       */
      public Builder addAllStrategySum(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureStrategySumIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, strategySum_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float strategy_sum = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStrategySum() {
        strategySum_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private int numActions_ ;
      /**
       * <code>int32 num_actions = 4;</code>
       * @return The numActions.
       */
      @java.lang.Override
      public int getNumActions() {
        return numActions_;
      }
      /**
       * <code>int32 num_actions = 4;</code>
       * @param value The numActions to set.
       * @return This builder for chaining.
       */
      public Builder setNumActions(int value) {
        
        numActions_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 num_actions = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumActions() {
        bitField0_ = (bitField0_ & ~0x00000008);
        numActions_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CFRNode)
    }

    // @@protoc_insertion_point(class_scope:CFRNode)
    private static final CFRNodeOuterClass.CFRNode DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CFRNodeOuterClass.CFRNode();
    }

    public static CFRNodeOuterClass.CFRNode getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CFRNode>
        PARSER = new com.google.protobuf.AbstractParser<CFRNode>() {
      @java.lang.Override
      public CFRNode parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CFRNode> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CFRNode> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public CFRNodeOuterClass.CFRNode getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NodeMapOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NodeMap)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Define a map from string keys to CFRNode values
     * </pre>
     *
     * <code>map&lt;string, .CFRNode&gt; nodes = 1;</code>
     */
    int getNodesCount();
    /**
     * <pre>
     * Define a map from string keys to CFRNode values
     * </pre>
     *
     * <code>map&lt;string, .CFRNode&gt; nodes = 1;</code>
     */
    boolean containsNodes(
        java.lang.String key);
    /**
     * Use {@link #getNodesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, CFRNodeOuterClass.CFRNode>
    getNodes();
    /**
     * <pre>
     * Define a map from string keys to CFRNode values
     * </pre>
     *
     * <code>map&lt;string, .CFRNode&gt; nodes = 1;</code>
     */
    java.util.Map<java.lang.String, CFRNodeOuterClass.CFRNode>
    getNodesMap();
    /**
     * <pre>
     * Define a map from string keys to CFRNode values
     * </pre>
     *
     * <code>map&lt;string, .CFRNode&gt; nodes = 1;</code>
     */
    /* nullable */
CFRNodeOuterClass.CFRNode getNodesOrDefault(
        java.lang.String key,
        /* nullable */
CFRNodeOuterClass.CFRNode defaultValue);
    /**
     * <pre>
     * Define a map from string keys to CFRNode values
     * </pre>
     *
     * <code>map&lt;string, .CFRNode&gt; nodes = 1;</code>
     */
    CFRNodeOuterClass.CFRNode getNodesOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code NodeMap}
   */
  public static final class NodeMap extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NodeMap)
      NodeMapOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NodeMap.newBuilder() to construct.
    private NodeMap(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NodeMap() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NodeMap();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CFRNodeOuterClass.internal_static_NodeMap_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetNodes();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CFRNodeOuterClass.internal_static_NodeMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CFRNodeOuterClass.NodeMap.class, CFRNodeOuterClass.NodeMap.Builder.class);
    }

    public static final int NODES_FIELD_NUMBER = 1;
    private static final class NodesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, CFRNodeOuterClass.CFRNode> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, CFRNodeOuterClass.CFRNode>newDefaultInstance(
                  CFRNodeOuterClass.internal_static_NodeMap_NodesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  CFRNodeOuterClass.CFRNode.getDefaultInstance());
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, CFRNodeOuterClass.CFRNode> nodes_;
    private com.google.protobuf.MapField<java.lang.String, CFRNodeOuterClass.CFRNode>
    internalGetNodes() {
      if (nodes_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            NodesDefaultEntryHolder.defaultEntry);
      }
      return nodes_;
    }
    public int getNodesCount() {
      return internalGetNodes().getMap().size();
    }
    /**
     * <pre>
     * Define a map from string keys to CFRNode values
     * </pre>
     *
     * <code>map&lt;string, .CFRNode&gt; nodes = 1;</code>
     */
    @java.lang.Override
    public boolean containsNodes(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetNodes().getMap().containsKey(key);
    }
    /**
     * Use {@link #getNodesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, CFRNodeOuterClass.CFRNode> getNodes() {
      return getNodesMap();
    }
    /**
     * <pre>
     * Define a map from string keys to CFRNode values
     * </pre>
     *
     * <code>map&lt;string, .CFRNode&gt; nodes = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, CFRNodeOuterClass.CFRNode> getNodesMap() {
      return internalGetNodes().getMap();
    }
    /**
     * <pre>
     * Define a map from string keys to CFRNode values
     * </pre>
     *
     * <code>map&lt;string, .CFRNode&gt; nodes = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
CFRNodeOuterClass.CFRNode getNodesOrDefault(
        java.lang.String key,
        /* nullable */
CFRNodeOuterClass.CFRNode defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, CFRNodeOuterClass.CFRNode> map =
          internalGetNodes().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Define a map from string keys to CFRNode values
     * </pre>
     *
     * <code>map&lt;string, .CFRNode&gt; nodes = 1;</code>
     */
    @java.lang.Override
    public CFRNodeOuterClass.CFRNode getNodesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, CFRNodeOuterClass.CFRNode> map =
          internalGetNodes().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetNodes(),
          NodesDefaultEntryHolder.defaultEntry,
          1);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, CFRNodeOuterClass.CFRNode> entry
           : internalGetNodes().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, CFRNodeOuterClass.CFRNode>
        nodes__ = NodesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, nodes__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CFRNodeOuterClass.NodeMap)) {
        return super.equals(obj);
      }
      CFRNodeOuterClass.NodeMap other = (CFRNodeOuterClass.NodeMap) obj;

      if (!internalGetNodes().equals(
          other.internalGetNodes())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetNodes().getMap().isEmpty()) {
        hash = (37 * hash) + NODES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetNodes().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CFRNodeOuterClass.NodeMap parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CFRNodeOuterClass.NodeMap parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CFRNodeOuterClass.NodeMap parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CFRNodeOuterClass.NodeMap parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CFRNodeOuterClass.NodeMap parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CFRNodeOuterClass.NodeMap parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CFRNodeOuterClass.NodeMap parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CFRNodeOuterClass.NodeMap parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CFRNodeOuterClass.NodeMap parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CFRNodeOuterClass.NodeMap parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CFRNodeOuterClass.NodeMap parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CFRNodeOuterClass.NodeMap parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CFRNodeOuterClass.NodeMap prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NodeMap}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NodeMap)
        CFRNodeOuterClass.NodeMapOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CFRNodeOuterClass.internal_static_NodeMap_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetNodes();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableNodes();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CFRNodeOuterClass.internal_static_NodeMap_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CFRNodeOuterClass.NodeMap.class, CFRNodeOuterClass.NodeMap.Builder.class);
      }

      // Construct using CFRNodeOuterClass.NodeMap.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        internalGetMutableNodes().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CFRNodeOuterClass.internal_static_NodeMap_descriptor;
      }

      @java.lang.Override
      public CFRNodeOuterClass.NodeMap getDefaultInstanceForType() {
        return CFRNodeOuterClass.NodeMap.getDefaultInstance();
      }

      @java.lang.Override
      public CFRNodeOuterClass.NodeMap build() {
        CFRNodeOuterClass.NodeMap result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public CFRNodeOuterClass.NodeMap buildPartial() {
        CFRNodeOuterClass.NodeMap result = new CFRNodeOuterClass.NodeMap(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(CFRNodeOuterClass.NodeMap result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.nodes_ = internalGetNodes();
          result.nodes_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CFRNodeOuterClass.NodeMap) {
          return mergeFrom((CFRNodeOuterClass.NodeMap)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CFRNodeOuterClass.NodeMap other) {
        if (other == CFRNodeOuterClass.NodeMap.getDefaultInstance()) return this;
        internalGetMutableNodes().mergeFrom(
            other.internalGetNodes());
        bitField0_ |= 0x00000001;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.MapEntry<java.lang.String, CFRNodeOuterClass.CFRNode>
                nodes__ = input.readMessage(
                    NodesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableNodes().getMutableMap().put(
                    nodes__.getKey(), nodes__.getValue());
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, CFRNodeOuterClass.CFRNode> nodes_;
      private com.google.protobuf.MapField<java.lang.String, CFRNodeOuterClass.CFRNode>
          internalGetNodes() {
        if (nodes_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              NodesDefaultEntryHolder.defaultEntry);
        }
        return nodes_;
      }
      private com.google.protobuf.MapField<java.lang.String, CFRNodeOuterClass.CFRNode>
          internalGetMutableNodes() {
        if (nodes_ == null) {
          nodes_ = com.google.protobuf.MapField.newMapField(
              NodesDefaultEntryHolder.defaultEntry);
        }
        if (!nodes_.isMutable()) {
          nodes_ = nodes_.copy();
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return nodes_;
      }
      public int getNodesCount() {
        return internalGetNodes().getMap().size();
      }
      /**
       * <pre>
       * Define a map from string keys to CFRNode values
       * </pre>
       *
       * <code>map&lt;string, .CFRNode&gt; nodes = 1;</code>
       */
      @java.lang.Override
      public boolean containsNodes(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetNodes().getMap().containsKey(key);
      }
      /**
       * Use {@link #getNodesMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, CFRNodeOuterClass.CFRNode> getNodes() {
        return getNodesMap();
      }
      /**
       * <pre>
       * Define a map from string keys to CFRNode values
       * </pre>
       *
       * <code>map&lt;string, .CFRNode&gt; nodes = 1;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, CFRNodeOuterClass.CFRNode> getNodesMap() {
        return internalGetNodes().getMap();
      }
      /**
       * <pre>
       * Define a map from string keys to CFRNode values
       * </pre>
       *
       * <code>map&lt;string, .CFRNode&gt; nodes = 1;</code>
       */
      @java.lang.Override
      public /* nullable */
CFRNodeOuterClass.CFRNode getNodesOrDefault(
          java.lang.String key,
          /* nullable */
CFRNodeOuterClass.CFRNode defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, CFRNodeOuterClass.CFRNode> map =
            internalGetNodes().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * Define a map from string keys to CFRNode values
       * </pre>
       *
       * <code>map&lt;string, .CFRNode&gt; nodes = 1;</code>
       */
      @java.lang.Override
      public CFRNodeOuterClass.CFRNode getNodesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, CFRNodeOuterClass.CFRNode> map =
            internalGetNodes().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearNodes() {
        bitField0_ = (bitField0_ & ~0x00000001);
        internalGetMutableNodes().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * Define a map from string keys to CFRNode values
       * </pre>
       *
       * <code>map&lt;string, .CFRNode&gt; nodes = 1;</code>
       */
      public Builder removeNodes(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableNodes().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, CFRNodeOuterClass.CFRNode>
          getMutableNodes() {
        bitField0_ |= 0x00000001;
        return internalGetMutableNodes().getMutableMap();
      }
      /**
       * <pre>
       * Define a map from string keys to CFRNode values
       * </pre>
       *
       * <code>map&lt;string, .CFRNode&gt; nodes = 1;</code>
       */
      public Builder putNodes(
          java.lang.String key,
          CFRNodeOuterClass.CFRNode value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableNodes().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * Define a map from string keys to CFRNode values
       * </pre>
       *
       * <code>map&lt;string, .CFRNode&gt; nodes = 1;</code>
       */
      public Builder putAllNodes(
          java.util.Map<java.lang.String, CFRNodeOuterClass.CFRNode> values) {
        internalGetMutableNodes().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000001;
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NodeMap)
    }

    // @@protoc_insertion_point(class_scope:NodeMap)
    private static final CFRNodeOuterClass.NodeMap DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CFRNodeOuterClass.NodeMap();
    }

    public static CFRNodeOuterClass.NodeMap getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NodeMap>
        PARSER = new com.google.protobuf.AbstractParser<NodeMap>() {
      @java.lang.Override
      public NodeMap parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<NodeMap> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NodeMap> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public CFRNodeOuterClass.NodeMap getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CFRNode_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CFRNode_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NodeMap_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NodeMap_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NodeMap_NodesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NodeMap_NodesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rCFRNode.proto\"Z\n\007CFRNode\022\022\n\nregret_sum" +
      "\030\001 \003(\002\022\020\n\010strategy\030\002 \003(\002\022\024\n\014strategy_sum" +
      "\030\003 \003(\002\022\023\n\013num_actions\030\004 \001(\005\"e\n\007NodeMap\022\"" +
      "\n\005nodes\030\001 \003(\0132\023.NodeMap.NodesEntry\0326\n\nNo" +
      "desEntry\022\013\n\003key\030\001 \001(\t\022\027\n\005value\030\002 \001(\0132\010.C" +
      "FRNode:\0028\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CFRNode_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CFRNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CFRNode_descriptor,
        new java.lang.String[] { "RegretSum", "Strategy", "StrategySum", "NumActions", });
    internal_static_NodeMap_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_NodeMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NodeMap_descriptor,
        new java.lang.String[] { "Nodes", });
    internal_static_NodeMap_NodesEntry_descriptor =
      internal_static_NodeMap_descriptor.getNestedTypes().get(0);
    internal_static_NodeMap_NodesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NodeMap_NodesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
